const mongoose = require('mongoose');
const teacherSchema = new mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:'User'
    },
    profile:{
        firstName:{
            type:String,
            required:true
        },
        lastName:{
            type:String,
            required:true
        },
        phoneNumber:{
            required:true,
            type:String,
        },
        gender:{
            type:String,
            enum:['male', 'female'],
            required:true,
        },
        address:{
            type:String,
            required:true
        },
        photo:{
            type:String,
            required:true,
        },
        dob:{
            type:Date,
            required:true,
        },
        pob:{
            type:String,
            required:true,
        },
        employeeId:{
            type:String,
            required:true
        },
        class:{
            type:String,
            required:true,
        },
        section:{
            type:String,
            required:true,
        },
        subjects:{
            type:[String],
            required:true
        },
        salary:{
            type:String,
            required:true,
        },
    },
    education:{
        university:{
            type:String,
            required:true,
        },
        degree:{
            type:String,
            required:true,
        },
        startDate:{
            type:Date,
            required:true,
        },
        endDate:{
            type:Date,
            required:true,
        },
        city:{
            type:String,
            required:true,
        },
    },
    createdBy:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:'Admin'
    },
    schoolId:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:'School'
    },
},{
    timestamps:true,
});
module.exports=mongoose.model('Teacher',teacherSchema)